apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: emailservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: emailservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        technology: "python"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: emailservice
          image: hrexed/emailservice-nootel:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=emailservicenotel
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          livenessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: emailservice
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: checkoutservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: checkoutservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
        - name: checkoutservice
          image: hrexed/checkoutservice-otel-metric:0.2
          ports:
            - containerPort: 5050
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
            - name: OTLP_SERVICE_ADDR
              value: "localhost"
            - name: OTLP_SERVICE_PORT
              value: "4317"
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice:5000"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: recommendationservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: recommendationservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        technology: "python"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: recommendationservice
          image: hrexed/recommendationservice-nootel:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          livenessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=recommendationservicenotel
          resources:
            requests:
              cpu: 100m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 450Mi

---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: recommendationservice
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6loadgenerator
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: loadgenerator
      product: k6
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
        product: k6
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: k6load
          image: hrexed/k6-prometheus-otlp:0.1
          imagePullPolicy: Always
          args: ["-u", "50", "-d", "24h"]
          env:
            - name: FRONTEND_ADDR
              value: "frontend"
            - name: K6_PROMETHEUS_REMOTE_URL
              value: http://PROM_SVC_TO_REPLACE.default.svc.cluster.local:9090/api/v1/write
            - name: OTLP_SERVICE_ADDR
              value: "localhost:4317"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: frontend
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: frontend
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
        - name: frontend
          # both look good
          #image: registry.lab.dynatrace.org/cloudplatform/hipster-shop-frontend
          image: hrexed/frontend-otel:0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-liveness-probe"
          env:
            - name: OTLP_SERVICE_ADDR
              value: "localhost"
            - name: OTLP_SERVICE_PORT
              value: "4317"
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendationservice:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "adservice:9555"
            - name: ENV_PLATFORM
              value: "gcp"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: paymentservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: paymentservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        technology: "nodejs"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: paymentservice
          image: gcr.io/dynatrace-demoability/paymentservice:9e830c2
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=paymentservicenotel
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: paymentservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: productcatalogservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: productcatalogservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: productcatalogservice
          image: hrexed/productcatalogservice-otel:0.1
          ports:
            - containerPort: 3550
          env:
            - name: OTLP_SERVICE_ADDR
              value: "localhost"
            - name: OTLP_SERVICE_PORT
              value: "4317"
            - name: PORT
              value: "3550"
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:3550"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:3550"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: productcatalogservice
  ports:
    - name: grpc
      port: 3550
      targetPort: 3550
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: cartservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: cartservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: cartservice
          image: hrexed/cartservice-otel:0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
          env:
            - name: OTLP_PORT
              value: "4317"
            - name: OTLP_HOST
              value: "localhost"
            - name: OTLP-SERVICENAME
              value: "cartservice"
            - name: REDIS_ADDR
              value: "redis-cart:6379"
            - name: PORT
              value: "7070"
            - name: LISTEN_ADDR
              value: "0.0.0.0"
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 512Mi
          readinessProbe:
            initialDelaySeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 10
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: cartservice
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: currencyservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: currencyservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        technology: "nodejs"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: currencyservice
          image: gcr.io/dynatrace-demoability/currencyservice:9e830c2
          ports:
            - name: grpc
              containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=currencyservicenotel
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7000"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:7000"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: currencyservice
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: shippingservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: shippingservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      containers:
        - name: shippingservice
          image: hrexed/shippingservice-otel:0.1
          ports:
            - containerPort: 50051
          env:
            - name: OTLP_SERVICE_ADDR
              value: "localhost"
            - name: OTLP_SERVICE_PORT
              value: "4317"
            - name: PORT
              value: "50051"
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: shippingservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: redis-cart
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: redis-cart
        product: hipster-shop
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
          resources:
            limits:
              memory: 256Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 200Mi
        - name: redis-exporter
          image: 'oliver006/redis_exporter:latest'
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9121
              protocol: TCP
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: redis-cart
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: hipster-shop
spec:
  selector:
    matchLabels:
      app: hipster-shop
      service: adservice
      product: hipster-shop
  template:
    metadata:
      labels:
        app: hipster-shop
        service: adservice
        product: hipster-shop
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        technology: "java"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: adservice
          image: hrexed/adservice-safe:0.1
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=adservicenotel
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: hipster-shop
spec:
  type: ClusterIP
  selector:
    app: hipster-shop
    service: adservice
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
---