apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: oteld
spec:
  mode: daemonset
  hostNetwork: true
  serviceAccount: otelcontribcol
  image: otel/opentelemetry-collector-contrib:0.61.0
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      zipkin:
        endpoint: 0.0.0.0:9411

      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: "localhost:65535"


    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800



      spanmetrics:
        metrics_exporter: prometheus

      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 30


    exporters:
      logging:



      prometheus:
        endpoint: "0.0.0.0:9090"
        namespace: default

      otlp/spanmetrics:
          endpoint: "localhost:55677"
          tls:
            insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp,zipkin]
          processors: [memory_limiter,spanmetrics,batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [prometheus]
        metrics/spanmetrics:
          receivers: [otlp/spanmetrics]
          exporters: [otlp/spanmetrics]